services:
  wikijs-thrasherverse:
    image: requarks/wiki:2
    container_name: thrasherverse-wikijs
    restart: unless-stopped
    depends_on:
      - postgres-thrasherverse
    ports:
      - ${PORT}:3000
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgres-thrasherverse
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - UPGRADE_DB=true
    volumes:
      - wikidata:/wiki/data

  postgres-thrasherverse:
    image: postgres:17
    container_name: thrasherverse-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  wikidata:
  postgres:
