services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    user: ${PUID}:${PGID}
    ports:
      - ${PORT}:80
    environment:
      - TZ=${TZ}
    volumes:
      - ntfy:/etc/ntfy
      - ntfy-cache:/var/cache/ntfy
    command:
      - serve

volumes:
  ntfy:
    external: true
  ntfy-cache:
    external: true