services:
  vs-code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: vs-code-server
    environment:
      - PUID=1000
      - PGID=1000
      - PASSWORD=${PASSWORD} #optional
#      - HASHED_PASSWORD= #optional
#      - SUDO_PASSWORD=password #optional
#      - SUDO_PASSWORD_HASH= #optional
#      - PROXY_DOMAIN=code-server.my.domain #optional
#      - DEFAULT_WORKSPACE=/config/workspace #optional
#      - PWA_APPNAME=code-server #optional
    volumes:
     - /etc/timezone:/etc/timezone
     - vs-code-server:/config
    ports:
      - ${PORT}:8443
    restart: unless-stopped

volumes:
  vs-code-server:
    external: true
