services:
  vs-code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: vs-code-server
    environment:
      - PUID=1000
      - PGID=1000
      - PASSWORD=${PASSWORD} #optional
      - PWA_APPNAME=ThrasherVerse Code #optional
    volumes:
     - /etc/timezone:/etc/timezone
     - ${WORKSPACE}:/config/workspace
     - vs-code-server:/config
    ports:
      - ${PORT}:8443
    restart: unless-stopped

volumes:
  vs-code-server:
    external: true