services:
  vs-code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: vs-code-server
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - PASSWORD=${PASSWORD}
      - PWA_APPNAME=ThrasherVerse Code
    volumes:
     - /etc/timezone:/etc/timezone
     - ${WORKSPACE}:/config/workspace
     - vs-code-server:/config
    ports:
      - ${PORT}:8443

volumes:
  vs-code-server:
    external: true