services:
  wiki-js-meshtastic:
    image: requarks/wiki:2
    container_name: wiki-js-meshtastic
    depends_on:
      - db
    ports:
      - ${PORT}:3000
    environment:
      - DB_TYPE=postgres
      - DB_HOST=wikijs-db-meshtastic
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - UPGRADE_DB=true
    volumes:
      - wikidata:/wiki/data
    restart: unless-stopped

  wikijs-db-meshtastic:
    image: postgres:17
    container_name: wikijs-db-meshtastic
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  wikidata:
    external: true
  pgdata:
    external: true