services:
  wiki-js-meshtastic:
    image: requarks/wiki:2
    container_name: wiki-js-meshtastic
    depends_on:
      - db
    ports:
      - ${PORT}:3000
    environment:
      - DB_TYPE=postgres
      - DB_HOST=wikijs-db-meshtastic
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - UPGRADE_DB=true
    volumes:
      - wikidata-meshtastic:/wiki/data
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - swarm

  wikijs-db-meshtastic:
    image: postgres:17
    container_name: wikijs-db-meshtastic
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata-meshtastic:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - swarm

volumes:
  wikidata-meshtastic:
    external: true
  pgdata-meshtastic:
    external: true

networks:
  swarm:
    external: true