services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - ${PORT}:81 # Admin Panel
    volumes:
      - /etc/timezone:/etc/timezone
      - nginx-proxy-manager:/data
      - nginx-proxy-manager:/etc/letsencrypt

volumes:
  nginx-proxy-manager:
    external: true
