services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: always
    networks:
      - frontend
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /etc/timezone:/etc/timezone
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data

volumes:
  portainer:
    external: true
