services:
  metube:
    image: alexta69/metube
    container_name: metube
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - target: 8081
        published: 8081
        mode: ingress
    networks:
      - frontend
    environment:
      - YTDL_OPTIONS={"ignoreerrors":true}

networks:
  frontend:
    driver: overlay