services:
  metube:
    image: alpine
    container_name: alpine
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - target: 80
        published: 8080
        mode: ingress
    networks:
      - frontend

networks:
  frontend:
    driver: overlay