services:
  test:
    image: alexta69/metube
    container_name: test
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - target: 8081
        published: 8081
        mode: ingress
    networks:
      - frontend

networks:
  frontend:
    driver: overlay