services:
  metube:
    image: alexta69/metube:latest
    ports:
      - ${PORT}:8081
    volumes:
      - metube:/downloads
    environment:
      - YTDL_OPTIONS={"ignoreerrors":true}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - swarm

volumes:
  metube:
    external: true

networks:
  swarm:
    external: true