services:
  metube:
    image: alpine
    container_name: alpine
    command: >
      sh -c "apk add --no-cache busybox-extras &&
         while true; do
           echo -e 'HTTP/1.1 200 OK\r\n\r\nResponse from container: ' \$(hostname) |
           nc -l -p 80;
         done"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - target: 80
        published: 8080
        mode: ingress
    networks:
      - frontend

networks:
  frontend:
    driver: overlay