services:
  metube:
    image: hashicorp/http-echo
    container_name: echo
    command: ["-text=Hello from $$(hostname)"]
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - target: 5678
        published: 8080
        mode: ingress
    networks:
      - frontend

networks:
  frontend:
    driver: overlay