services:
  peanut:
    image: brandawg93/peanut:latest
    container_name: PeaNUT
    restart: unless-stopped
    ports:
      - ${PORT}:8080
    environment:
      - NUT_HOST=${NUT_HOST}
      - NUT_PORT=${NUT_PORT}