services:
  metube:
    image: alexta69/metube:latest
    container_name: metube
    restart: unless-stopped
    ports:
      - ${PORT}:8081
    volumes:
      - metube:/downloads
    environment:
      - YTDL_OPTIONS={"ignoreerrors":true}

volumes:
  metube:
    external: true